apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
  spec:
    initContainers:
    - name: python-populate-db
      image: necrutatoru/scratch-insert-data:1.0.0
      env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_HOST
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PORT
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DB_PASSWORD
      - name: DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DATABASE_NAME
      - name: TABLE_NAME
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: TABLE_NAME
    containers:
    - name: express-app
      image: necrutatoru/scratch-api:1.0.0
      ports:
      - containerPort: 8080
      env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_HOST
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PORT
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DB_PASSWORD
      - name: DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DATABASE_NAME
      - name: TABLE_NAME
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: TABLE_NAME
