apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
  spec:
    containers:
    - name: mysql
      image: mysql:5.7
      ports:
      - containerPort: 3306
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: DB_PASSWORD
      volumeMounts:
      - name: mysql-storage
        mountPath: /var/lib/mysql
    volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
      